#!/bin/bash

# unban IPs from log, generated by cf.banlist.sh

X_AUTH_KEY="............."
X_AUTH_EMAIL="........."
CONTENT_TYPE="application/json"

LOG_DIR="/home/user/bin/cf/log"
LOG="${LOG_DIR}/bannedip.log"
WEB_LOG="/var/log/nginx/site.access.log"


while read IP
do

curl -X DELETE "https://api.cloudflare.com/client/v4/user/firewall/access_rules/rules/${IP}" \
     -H "X-Auth-Email: ${X_AUTH_EMAIL}" \
     -H "X-Auth-Key: ${X_AUTH_KEY}" \
     -H "Content-Type: ${CONTENT_TYPE}"
done < ${LOG}

#rm -rf ${LOG_DIR}/autoban/*